name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Main Branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Adding secret
        run: |
          echo "spring.datasource.password= $DEV_PROP_FILE" >> backend2shine/src/main/resources/application.properties
          cat src/main/resources/application.properties
      shell: bash
      env:
        DEV_PROP_FILE: ${{secrets.POSTGRES_PW}}


      - name: Build Initial with Gradle
        working-directory: ./backend2shine
        run: ./gradlew build
